
    document.addEventListener('alpine:init', () => {
        Alpine.data('methodology', () => ({
            intro : true,
            thematicDropdown: false,
            thematic : true,
            economicdev : false,
            qframework1 : false,
            bConduct : false,
            qframework2 : false,
            lManagement : false,
            qframework3 : false,
            cWellbeing : false,
            qframework4 : false,
            wCondition : false,
            qframework5 : false,
            eResponsibility : false,
            qframework6 : false,
            loadingSkeleton: false,

            toogleIntro() {
                this.intro = true,
                this.economicdev = false,
                this.qframework1 = false,
                this.qframework2 = false,
                this.bConduct = false,
                this.lManagement = false,
                this.qframework3 = false,
                this.cWellbeing = false,
                this.qframework4 = false,
                this.wCondition = false,
                this.qframework5 = false,
                this.eResponsibility = false,
                this.qframework6 = false
            },
            toogleEconomicdev(){
                this.intro = false,
                this.economicdev =  true,
                this.qframework1 = false,
                this.qframework2 = false,
                this.bConduct = false,
                this.lManagement = false,
                this.qframework3 = false,
                this.cWellbeing = false,
                this.qframework4 = false,
                this.wCondition = false,
                this.qframework5 = false,
                this.eResponsibility = false,
                this.qframework6 = false
            },
            toogleqFramework1(){
                this.intro = false,
                this.economicdev =  false,
                this.qframework1 = true,
                this.qframework2 = false,
                this.bConduct = false,
                this.lManagement = false,
                this.qframework3 = false,
                this.cWellbeing = false,
                this.qframework4 = false,
                this.wCondition = false,
                this.qframework5 = false,
                this.eResponsibility = false,
                this.qframework6 = false
            },
            tooglebConduct(){
                this.intro = false,
                this.economicdev =  false,
                this.qframework1 = false,
                this.qframework2 = false,
                this.bConduct = true,
                this.lManagement = false,
                this.qframework3 = false,
                this.cWellbeing = false,
                this.qframework4 = false,
                this.wCondition = false,
                this.qframework5 = false,
                this.eResponsibility = false,
                this.qframework6 = false
            },
            toogleqFramework2(){
                this.intro = false,
                this.economicdev =  false,
                this.qframework1 = false,
                this.qframework2 = true,
                this.bConduct = false,
                this.lManagement = false,
                this.qframework3 = false,
                this.cWellbeing = false,
                this.qframework4 = false,
                this.wCondition = false,
                this.qframework5 = false,
                this.eResponsibility = false,
                this.qframework6 = false
            },
            tooglelManagement(){
                this.intro = false,
                this.economicdev =  false,
                this.qframework1 = false,
                this.qframework2 = false,
                this.bConduct = false,
                this.lManagement = true,
                this.qframework3 = false,
                this.cWellbeing = false,
                this.qframework4 = false,
                this.wCondition = false,
                this.qframework5 = false,
                this.eResponsibility = false,
                this.qframework6 = false
            },
            toogleqFramework3(){
                this.intro = false,
                this.economicdev =  false,
                this.qframework1 = false,
                this.qframework2 = false,
                this.bConduct = false,
                this.lManagement = false,
                this.qframework3 = true,
                this.cWellbeing = false,
                this.qframework4 = false,
                this.wCondition = false,
                this.qframework5 = false,
                this.eResponsibility = false,
                this.qframework6 = false
            },
            tooglecWellbeing(){
                this.intro = false,
                this.economicdev =  false,
                this.qframework1 = false,
                this.qframework2 = false,
                this.bConduct = false,
                this.lManagement = false,
                this.qframework3 = false,
                this.cWellbeing = true,
                this.qframework4 = false,
                this.wCondition = false,
                this.qframework5 = false,
                this.eResponsibility = false,
                this.qframework6 = false
            },
            toogleqFramework4(){
                this.intro = false,
                this.economicdev =  false,
                this.qframework1 = false,
                this.qframework2 = false,
                this.bConduct = false,
                this.lManagement = false,
                this.qframework3 = false,
                this.cWellbeing = false,
                this.qframework4 = true,
                this.wCondition = false,
                this.qframework5 = false,
                this.eResponsibility = false,
                this.qframework6 = false
            },
            tooglewCondition(){
                this.intro = false,
                this.economicdev =  false,
                this.qframework1 = false,
                this.qframework2 = false,
                this.bConduct = false,
                this.lManagement = false,
                this.qframework3 = false,
                this.cWellbeing = false,
                this.qframework4 = false,
                this.wCondition = true,
                this.qframework5 = false,
                this.eResponsibility = false,
                this.qframework6 = false
            },
            toogleqFramework5(){
                this.intro = false,
                this.economicdev =  false,
                this.qframework1 = false,
                this.qframework2 = false,
                this.bConduct = false,
                this.lManagement = false,
                this.qframework3 = false,
                this.cWellbeing = false,
                this.qframework4 = false,
                this.wCondition = false,
                this.qframework5 = true,
                this.eResponsibility = false,
                this.qframework6 = false
            },
            toogleeResponsibility(){
                this.intro = false,
                this.economicdev =  false,
                this.qframework1 = false,
                this.qframework2 = false,
                this.bConduct = false,
                this.lManagement = false,
                this.qframework3 = false,
                this.cWellbeing = false,
                this.qframework4 = false,
                this.wCondition = false,
                this.qframework5 = false,
                this.eResponsibility = true,
                this.qframework6 = false
            },
            toogleqFramework6(){
                this.intro = false,
                this.economicdev =  false,
                this.qframework1 = false,
                this.qframework2 = false,
                this.bConduct = false,
                this.lManagement = false,
                this.qframework3 = false,
                this.cWellbeing = false,
                this.qframework4 = false,
                this.wCondition = false,
                this.qframework5 = false,
                this.eResponsibility = false,
                this.qframework6 = true
            }
        }))


        Alpine.data('qframework6', () => ({
            F01 : false,
            F02 : false,
            F03 : false,
            F04 : false,
            F05 : false,
            F06 : false,
            F07 : false,
            F08 : false,
            F011 : false,
            F012 : false,
            F023 : false,
            F021 : false,
            F022 : false,
            F031 : false,
            F032 : false,
            F033 : false,
            F041 : false,
            F051 : false,
            F052 : false,
            F061 : false,
            F062 : false,
            F063 : false,
            F071 : false,
            F081 : false,
            F082 : false,

            toogleF01(){
                this.F01 = ! this.F01,
                this.F02 = false,
                this.F03 = false,
                this.F04 = false,
                this.F05 = false,
                this.F06 = false,
                this.F07 = false,
                this.F08 = false,
                this.F011 = false,
                this.F012 = false,
                this.F023 = false,
                this.F021 = false,
                this.F022 = false,
                this.F031 = false,
                this.F032 = false,
                this.F033 = false,
                this.F041 = false,
                this.F051 = false,
                this.F052 = false,
                this.F061 = false,
                this.F062 = false,
                this.F063 = false,
                this.F071 = false,
                this.F081 = false,
                this.F082 = false,
                window.scrollTo({
                    top: 350,
                    left: 1500,
                    behavior: 'smooth'
                })
            },
            toogleF02(){
                this.F01 = false,
                this.F02 = ! this.F02,
                this.F03 = false,
                this.F04 = false,
                this.F05 = false,
                this.F06 = false,
                this.F07 = false,
                this.F08 = false,
                this.F011 = false,
                this.F012 = false,
                this.F023 = false,
                this.F021 = false,
                this.F022 = false,
                this.F031 = false,
                this.F032 = false,
                this.F033 = false,
                this.F041 = false,
                this.F051 = false,
                this.F052 = false,
                this.F061 = false,
                this.F062 = false,
                this.F063 = false,
                this.F071 = false,
                this.F081 = false,
                this.F082 = false,
                window.scrollTo({
                    top: 350,
                    left: 1500,
                    behavior: 'smooth'
                  })
            },
            toogleF03(){
                this.F01 = false,
                this.F02 = false,
                this.F03 = ! this.F03,
                this.F04 = false,
                this.F05 = false,
                this.F06 = false,
                this.F07 = false,
                this.F08 = false,
                this.F011 = false,
                this.F012 = false,
                this.F023 = false,
                this.F021 = false,
                this.F022 = false,
                this.F031 = false,
                this.F032 = false,
                this.F033 = false,
                this.F041 = false,
                this.F051 = false,
                this.F052 = false,
                this.F061 = false,
                this.F062 = false,
                this.F063 = false,
                this.F071 = false,
                this.F081 = false,
                this.F082 = false,
                window.scrollTo({
                    top: 350,
                    left: 1500,
                    behavior: 'smooth'
                })

            },
            toogleF04(){
                this.F01 = false,
                this.F02 = false,
                this.F03 = false,
                this.F04 = ! this.F04,
                this.F05 = false,
                this.F06 = false,
                this.F07 = false,
                this.F08 = false,
                this.F011 = false,
                this.F012 = false,
                this.F023 = false,
                this.F021 = false,
                this.F022 = false,
                this.F031 = false,
                this.F032 = false,
                this.F033 = false,
                this.F041 = false,
                this.F051 = false,
                this.F052 = false,
                this.F061 = false,
                this.F062 = false,
                this.F063 = false,
                this.F071 = false,
                this.F081 = false,
                this.F082 = false,
                window.scrollTo({
                    top: 350,
                    left: 1500,
                    behavior: 'smooth'
                })

            },
            toogleF05(){
                this.F01 = false,
                this.F02 = false,
                this.F03 = false,
                this.F04 = false,
                this.F05 = ! this.F05,
                this.F06 = false,
                this.F07 = false,
                this.F08 = false,
                this.F011 = false,
                this.F012 = false,
                this.F023 = false,
                this.F021 = false,
                this.F022 = false,
                this.F031 = false,
                this.F032 = false,
                this.F033 = false,
                this.F041 = false,
                this.F051 = false,
                this.F052 = false,
                this.F061 = false,
                this.F062 = false,
                this.F063 = false,
                this.F071 = false,
                this.F081 = false,
                this.F082 = false,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                })

            },
            toogleF05(){
                this.F01 = false,
                this.F02 = false,
                this.F03 = false,
                this.F04 = false,
                this.F05 = ! this.F05,
                this.F06 = false,
                this.F07 = false,
                this.F08 = false,
                this.F011 = false,
                this.F012 = false,
                this.F023 = false,
                this.F021 = false,
                this.F022 = false,
                this.F031 = false,
                this.F032 = false,
                this.F033 = false,
                this.F041 = false,
                this.F051 = false,
                this.F052 = false,
                this.F061 = false,
                this.F062 = false,
                this.F063 = false,
                this.F071 = false,
                this.F081 = false,
                this.F082 = false,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                })

            },
            toogleF06(){
                this.F01 = false,
                this.F02 = false,
                this.F03 = false,
                this.F04 = false,
                this.F05 = false,
                this.F06 = ! this.F06,
                this.F07 = false,
                this.F08 = false,
                this.F011 = false,
                this.F012 = false,
                this.F023 = false,
                this.F021 = false,
                this.F022 = false,
                this.F031 = false,
                this.F032 = false,
                this.F033 = false,
                this.F041 = false,
                this.F051 = false,
                this.F052 = false,
                this.F061 = false,
                this.F062 = false,
                this.F063 = false,
                this.F071 = false,
                this.F081 = false,
                this.F082 = false,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                  })

            },
            toogleF07(){
                this.F01 = false,
                this.F02 = false,
                this.F03 = false,
                this.F04 = false,
                this.F05 = false,
                this.F06 = false,
                this.F07 = ! this.F07,
                this.F08 = false,
                this.F011 = false,
                this.F012 = false,
                this.F023 = false,
                this.F021 = false,
                this.F022 = false,
                this.F031 = false,
                this.F032 = false,
                this.F033 = false,
                this.F041 = false,
                this.F051 = false,
                this.F052 = false,
                this.F061 = false,
                this.F062 = false,
                this.F063 = false,
                this.F071 = false,
                this.F081 = false,
                this.F082 = false,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                  })
            },
            toogleF08(){
                this.F01 = false,
                this.F02 = false,
                this.F03 = false,
                this.F04 = false,
                this.F05 = false,
                this.F06 = false,
                this.F07 = false,
                this.F08 = ! this.F08,
                this.F011 = false,
                this.F012 = false,
                this.F023 = false,
                this.F021 = false,
                this.F022 = false,
                this.F031 = false,
                this.F032 = false,
                this.F033 = false,
                this.F041 = false,
                this.F051 = false,
                this.F052 = false,
                this.F061 = false,
                this.F062 = false,
                this.F063 = false,
                this.F071 = false,
                this.F081 = false,
                this.F082 = false,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                  })
            },
            toogleF011(){
                this.F01 = false,
                this.F02 = false,
                this.F03 = false,
                this.F04 = false,
                this.F05 = false,
                this.F06 = false,
                this.F07 = false,
                this.F08 = false,
                this.F011 = ! this.F011,
                this.F012 = false,
                this.F023 = false,
                this.F021 = false,
                this.F022 = false,
                this.F031 = false,
                this.F032 = false,
                this.F033 = false,
                this.F041 = false,
                this.F051 = false,
                this.F052 = false,
                this.F061 = false,
                this.F062 = false,
                this.F063 = false,
                this.F071 = false,
                this.F081 = false,
                this.F082 = false,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                  })
            },
            toogleF012(){
                this.F01 = false,
                this.F02 = false,
                this.F03 = false,
                this.F04 = false,
                this.F05 = false,
                this.F06 = false,
                this.F07 = false,
                this.F08 = false,
                this.F011 = false,
                this.F012 = ! this.F012,
                this.F023 = false,
                this.F021 = false,
                this.F022 = false,
                this.F031 = false,
                this.F032 = false,
                this.F033 = false,
                this.F041 = false,
                this.F051 = false,
                this.F052 = false,
                this.F061 = false,
                this.F062 = false,
                this.F063 = false,
                this.F071 = false,
                this.F081 = false,
                this.F082 = false,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                  })
            },
            toogleF021(){
                this.F01 = false,
                this.F02 = false,
                this.F03 = false,
                this.F04 = false,
                this.F05 = false,
                this.F06 = false,
                this.F07 = false,
                this.F08 = false,
                this.F011 = false,
                this.F012 = false,
                this.F023 = false,
                this.F021 = ! this.F021 ,
                this.F022 = false,
                this.F031 = false,
                this.F032 = false,
                this.F033 = false,
                this.F041 = false,
                this.F051 = false,
                this.F052 = false,
                this.F061 = false,
                this.F062 = false,
                this.F063 = false,
                this.F071 = false,
                this.F081 = false,
                this.F082 = false,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                  })
            },
            toogleF022(){
                this.F01 = false,
                this.F02 = false,
                this.F03 = false,
                this.F04 = false,
                this.F05 = false,
                this.F06 = false,
                this.F07 = false,
                this.F08 = false,
                this.F011 = false,
                this.F012 = false,
                this.F023 = false,
                this.F021 = false,
                this.F022 = ! this.F022,
                this.F031 = false,
                this.F032 = false,
                this.F033 = false,
                this.F041 = false,
                this.F051 = false,
                this.F052 = false,
                this.F061 = false,
                this.F062 = false,
                this.F063 = false,
                this.F071 = false,
                this.F081 = false,
                this.F082 = false,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                  })
            },
            toogleF023(){
                this.F01 = false,
                this.F02 = false,
                this.F03 = false,
                this.F04 = false,
                this.F05 = false,
                this.F06 = false,
                this.F07 = false,
                this.F08 = false,
                this.F011 = false,
                this.F012 = false,
                this.F023 = ! this.F023,
                this.F021 = false,
                this.F022 = false,
                this.F031 = false,
                this.F032 = false,
                this.F033 = false,
                this.F041 = false,
                this.F051 = false,
                this.F052 = false,
                this.F061 = false,
                this.F062 = false,
                this.F063 = false,
                this.F071 = false,
                this.F081 = false,
                this.F082 = false,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                  })
            },
            toogleF031(){
                this.F01 = false,
                this.F02 = false,
                this.F03 = false,
                this.F04 = false,
                this.F05 = false,
                this.F06 = false,
                this.F07 = false,
                this.F08 = false,
                this.F011 = false,
                this.F012 = false,
                this.F023 = false,
                this.F021 = false,
                this.F022 = false,
                this.F031 = ! this.F031,
                this.F032 = false,
                this.F033 = false,
                this.F041 = false,
                this.F051 = false,
                this.F052 = false,
                this.F061 = false,
                this.F062 = false,
                this.F063 = false,
                this.F071 = false,
                this.F081 = false,
                this.F082 = false,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                  })
            },
            toogleF032(){
                this.F01 = false,
                this.F02 = false,
                this.F03 = false,
                this.F04 = false,
                this.F05 = false,
                this.F06 = false,
                this.F07 = false,
                this.F08 = false,
                this.F011 = false,
                this.F012 = false,
                this.F023 = false,
                this.F021 = false,
                this.F022 = false,
                this.F031 = false,
                this.F032 = ! this.F032,
                this.F033 = false,
                this.F041 = false,
                this.F051 = false,
                this.F052 = false,
                this.F061 = false,
                this.F062 = false,
                this.F063 = false,
                this.F071 = false,
                this.F081 = false,
                this.F082 = false,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                  })
            },
            toogleF033(){
                this.F01 = false,
                this.F02 = false,
                this.F03 = false,
                this.F04 = false,
                this.F05 = false,
                this.F06 = false,
                this.F07 = false,
                this.F08 = false,
                this.F011 = false,
                this.F012 = false,
                this.F023 = false,
                this.F021 = false,
                this.F022 = false,
                this.F031 = false,
                this.F032 = false,
                this.F033 = ! this.F033,
                this.F041 = false,
                this.F051 = false,
                this.F052 = false,
                this.F061 = false,
                this.F062 = false,
                this.F063 = false,
                this.F071 = false,
                this.F081 = false,
                this.F082 = false,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                  })
            },
            toogleF041(){
                this.F01 = false,
                this.F02 = false,
                this.F03 = false,
                this.F04 = false,
                this.F05 = false,
                this.F06 = false,
                this.F07 = false,
                this.F08 = false,
                this.F011 = false,
                this.F012 = false,
                this.F023 = false,
                this.F021 = false,
                this.F022 = false,
                this.F031 = false,
                this.F032 = false,
                this.F033 = false,
                this.F041 = ! this.F041,
                this.F051 = false,
                this.F052 = false,
                this.F061 = false,
                this.F062 = false,
                this.F063 = false,
                this.F071 = false,
                this.F081 = false,
                this.F082 = false,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                  })
            },
            toogleF051(){
                this.F01 = false,
                this.F02 = false,
                this.F03 = false,
                this.F04 = false,
                this.F05 = false,
                this.F06 = false,
                this.F07 = false,
                this.F08 = false,
                this.F011 = false,
                this.F012 = false,
                this.F023 = false,
                this.F021 = false,
                this.F022 = false,
                this.F031 = false,
                this.F032 = false,
                this.F033 = false,
                this.F041 = false,
                this.F051 = ! this.F051,
                this.F052 = false,
                this.F061 = false,
                this.F062 = false,
                this.F063 = false,
                this.F071 = false,
                this.F081 = false,
                this.F082 = false,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                  })
            },
            toogleF052(){
                this.F01 = false,
                this.F02 = false,
                this.F03 = false,
                this.F04 = false,
                this.F05 = false,
                this.F06 = false,
                this.F07 = false,
                this.F08 = false,
                this.F011 = false,
                this.F012 = false,
                this.F023 = false,
                this.F021 = false,
                this.F022 = false,
                this.F031 = false,
                this.F032 = false,
                this.F033 = false,
                this.F041 = false,
                this.F051 = false,
                this.F052 = ! this.F052,
                this.F061 = false,
                this.F062 = false,
                this.F063 = false,
                this.F071 = false,
                this.F081 = false,
                this.F082 = false,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                  })
            },
            toogleF061(){
                this.F01 = false,
                this.F02 = false,
                this.F03 = false,
                this.F04 = false,
                this.F05 = false,
                this.F06 = false,
                this.F07 = false,
                this.F08 = false,
                this.F011 = false,
                this.F012 = false,
                this.F023 = false,
                this.F021 = false,
                this.F022 = false,
                this.F031 = false,
                this.F032 = false,
                this.F033 = false,
                this.F041 = false,
                this.F051 = false,
                this.F052 = false,
                this.F061 = ! this.F061,
                this.F062 = false,
                this.F063 = false,
                this.F071 = false,
                this.F081 = false,
                this.F082 = false,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                  })
            },
            toogleF062(){
                this.F01 = false,
                this.F02 = false,
                this.F03 = false,
                this.F04 = false,
                this.F05 = false,
                this.F06 = false,
                this.F07 = false,
                this.F08 = false,
                this.F011 = false,
                this.F012 = false,
                this.F023 = false,
                this.F021 = false,
                this.F022 = false,
                this.F031 = false,
                this.F032 = false,
                this.F033 = false,
                this.F041 = false,
                this.F051 = false,
                this.F052 = false,
                this.F061 = false,
                this.F062 = ! this.F062,
                this.F063 = false,
                this.F071 = false,
                this.F081 = false,
                this.F082 = false,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                  })
            },
            toogleF063(){
                this.F01 = false,
                this.F02 = false,
                this.F03 = false,
                this.F04 = false,
                this.F05 = false,
                this.F06 = false,
                this.F07 = false,
                this.F08 = false,
                this.F011 = false,
                this.F012 = false,
                this.F023 = false,
                this.F021 = false,
                this.F022 = false,
                this.F031 = false,
                this.F032 = false,
                this.F033 = false,
                this.F041 = false,
                this.F051 = false,
                this.F052 = false,
                this.F061 = false,
                this.F062 = false,
                this.F063 = ! this.F063,
                this.F071 = false,
                this.F081 = false,
                this.F082 = false,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                  })
            },
            toogleF071(){
                this.F01 = false,
                this.F02 = false,
                this.F03 = false,
                this.F04 = false,
                this.F05 = false,
                this.F06 = false,
                this.F07 = false,
                this.F08 = false,
                this.F011 = false,
                this.F012 = false,
                this.F023 = false,
                this.F021 = false,
                this.F022 = false,
                this.F031 = false,
                this.F032 = false,
                this.F033 = false,
                this.F041 = false,
                this.F051 = false,
                this.F052 = false,
                this.F061 = false,
                this.F062 = false,
                this.F063 = false,
                this.F071 = ! this.F071,
                this.F081 = false,
                this.F082 = false,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                  })
            },
            toogleF081(){
                this.F01 = false,
                this.F02 = false,
                this.F03 = false,
                this.F04 = false,
                this.F05 = false,
                this.F06 = false,
                this.F07 = false,
                this.F08 = false,
                this.F011 = false,
                this.F012 = false,
                this.F023 = false,
                this.F021 = false,
                this.F022 = false,
                this.F031 = false,
                this.F032 = false,
                this.F033 = false,
                this.F041 = false,
                this.F051 = false,
                this.F052 = false,
                this.F061 = false,
                this.F062 = false,
                this.F063 = false,
                this.F071 = false,
                this.F081 = ! this.F081,
                this.F082 = false,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                  })
            },
            toogleF082(){
                this.F01 = false,
                this.F02 = false,
                this.F03 = false,
                this.F04 = false,
                this.F05 = false,
                this.F06 = false,
                this.F07 = false,
                this.F08 = false,
                this.F011 = false,
                this.F012 = false,
                this.F023 = false,
                this.F021 = false,
                this.F022 = false,
                this.F031 = false,
                this.F032 = false,
                this.F033 = false,
                this.F041 = false,
                this.F051 = false,
                this.F052 = false,
                this.F061 = false,
                this.F062 = false,
                this.F063 = false,
                this.F071 = false,
                this.F081 = false,
                this.F082 = ! this.F082,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                  })
            },
        }))

        Alpine.data('qframework2', () => ({
            B01 : false,
            B02 : false,
            B03 : false,
            B04 : false,
            B05 : false,
            B06 : false,
            B07 : false,
            B08 : false,
            B011 : false,
            B012 : false,
            B013 : false,
            B021 : false,
            B022 : false,
            B031 : false,
            B041 : false,
            B051 : false,
            B061 : false,
            B071 : false,
            B081 : false,

            toogleB01(){
                this.B01 = ! this.B01,
                this.B02 = false,
                this.B03 = false,
                this.B04 = false,
                this.B05 = false,
                this.B06 = false,
                this.B07 = false,
                this.B08 = false,
                this.B011 = false,
                this.B012 = false,
                this.B013 = false,
                this.B021 = false,
                this.B022 = false,
                this.B031 = false,
                this.B041 = false,
                this.B051 = false,
                this.B061 = false,
                this.B071 = false,
                this.B081 = false,
                window.scrollTo({
                    top: 350,
                    left: 1500,
                    behavior: 'smooth'
                })
            },
            toogleB02(){
                this.B01 = false,
                this.B02 = ! this.B02,
                this.B03 = false,
                this.B04 = false,
                this.B05 = false,
                this.B06 = false,
                this.B07 = false,
                this.B08 = false,
                this.B011 = false,
                this.B012 = false,
                this.B013 = false,
                this.B021 = false,
                this.B022 = false,
                this.B031 = false,
                this.B041 = false,
                this.B051 = false,
                this.B061 = false,
                this.B071 = false,
                this.B081 = false,
                window.scrollTo({
                    top: 350,
                    left: 1500,
                    behavior: 'smooth'
                  })
            },
            toogleB03(){
                this.B01 = false,
                this.B02 = false,
                this.B03 = ! this.B03,
                this.B04 = false,
                this.B05 = false,
                this.B06 = false,
                this.B07 = false,
                this.B08 = false,
                this.B011 = false,
                this.B012 = false,
                this.B013 = false,
                this.B021 = false,
                this.B022 = false,
                this.B031 = false,
                this.B041 = false,
                this.B051 = false,
                this.B061 = false,
                this.B071 = false,
                this.B081 = false,
                window.scrollTo({
                    top: 350,
                    left: 1500,
                    behavior: 'smooth'
                  })
            },
            toogleB04(){
                this.B01 = false,
                this.B02 = false,
                this.B03 = false,
                this.B04 = ! this.B04,
                this.B05 = false,
                this.B06 = false,
                this.B07 = false,
                this.B08 = false,
                this.B011 = false,
                this.B012 = false,
                this.B013 = false,
                this.B021 = false,
                this.B022 = false,
                this.B031 = false,
                this.B041 = false,
                this.B051 = false,
                this.B061 = false,
                this.B071 = false,
                this.B081 = false,
                window.scrollTo({
                    top: 350,
                    left: 1500,
                    behavior: 'smooth'
                  })
            },
            toogleB05(){
                this.B01 = false,
                this.B02 = false,
                this.B03 = false,
                this.B04 = false,
                this.B05 = ! this.B05,
                this.B06 = false,
                this.B07 = false,
                this.B08 = false,
                this.B011 = false,
                this.B012 = false,
                this.B013 = false,
                this.B021 = false,
                this.B022 = false,
                this.B031 = false,
                this.B041 = false,
                this.B051 = false,
                this.B061 = false,
                this.B071 = false,
                this.B081 = false,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                  })
            },
            toogleB06(){
                this.B01 = false,
                this.B02 = false,
                this.B03 = false,
                this.B04 = false,
                this.B05 = false,
                this.B06 = ! this.B06,
                this.B07 = false,
                this.B08 = false,
                this.B011 = false,
                this.B012 = false,
                this.B013 = false,
                this.B021 = false,
                this.B022 = false,
                this.B031 = false,
                this.B041 = false,
                this.B051 = false,
                this.B061 = false,
                this.B071 = false,
                this.B081 = false,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                  })
            },
            toogleB07(){
                this.B01 = false,
                this.B02 = false,
                this.B03 = false,
                this.B04 = false,
                this.B05 = false,
                this.B06 = false,
                this.B07 = ! this.B07,
                this.B08 = false,
                this.B011 = false,
                this.B012 = false,
                this.B013 = false,
                this.B021 = false,
                this.B022 = false,
                this.B031 = false,
                this.B041 = false,
                this.B051 = false,
                this.B061 = false,
                this.B071 = false,
                this.B081 = false,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                  })
            },
            toogleB08(){
                this.B01 = false,
                this.B02 = false,
                this.B03 = false,
                this.B04 = false,
                this.B05 = false,
                this.B06 = false,
                this.B07 = false,
                this.B08 = ! this.B08,
                this.B011 = false,
                this.B012 = false,
                this.B013 = false,
                this.B021 = false,
                this.B022 = false,
                this.B031 = false,
                this.B041 = false,
                this.B051 = false,
                this.B061 = false,
                this.B071 = false,
                this.B081 = false,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                  })
            },
            toogleB011(){
                this.B01 = false,
                this.B02 = false,
                this.B03 = false,
                this.B04 = false,
                this.B05 = false,
                this.B06 = false,
                this.B07 = false,
                this.B08 = false,
                this.B011 = ! this.B011,
                this.B012 = false,
                this.B013 = false,
                this.B021 = false,
                this.B022 = false,
                this.B031 = false,
                this.B041 = false,
                this.B051 = false,
                this.B061 = false,
                this.B071 = false,
                this.B081 = false,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                  })
            },
            toogleB012(){
                this.B01 = false,
                this.B02 = false,
                this.B03 = false,
                this.B04 = false,
                this.B05 = false,
                this.B06 = false,
                this.B07 = false,
                this.B08 = false,
                this.B011 = false,
                this.B012 = ! this.B012,
                this.B013 = false,
                this.B021 = false,
                this.B022 = false,
                this.B031 = false,
                this.B041 = false,
                this.B051 = false,
                this.B061 = false,
                this.B071 = false,
                this.B081 = false,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                  })
            },
            toogleB013(){
                this.B01 = false,
                this.B02 = false,
                this.B03 = false,
                this.B04 = false,
                this.B05 = false,
                this.B06 = false,
                this.B07 = false,
                this.B08 = false,
                this.B011 = false,
                this.B012 = false,
                this.B013 = ! this.B013,
                this.B021 = false,
                this.B022 = false,
                this.B031 = false,
                this.B041 = false,
                this.B051 = false,
                this.B061 = false,
                this.B071 = false,
                this.B081 = false,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                  })
            },
            toogleB021(){
                this.B01 = false,
                this.B02 = false,
                this.B03 = false,
                this.B04 = false,
                this.B05 = false,
                this.B06 = false,
                this.B07 = false,
                this.B08 = false,
                this.B011 = false,
                this.B012 = false,
                this.B013 = false,
                this.B021 = ! this.B021,
                this.B022 = false,
                this.B031 = false,
                this.B041 = false,
                this.B051 = false,
                this.B061 = false,
                this.B071 = false,
                this.B081 = false,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                  })
            },
            toogleB022(){
                this.B01 = false,
                this.B02 = false,
                this.B03 = false,
                this.B04 = false,
                this.B05 = false,
                this.B06 = false,
                this.B07 = false,
                this.B08 = false,
                this.B011 = false,
                this.B012 = false,
                this.B013 = false,
                this.B021 = false,
                this.B022 = ! this.B022,
                this.B031 = false,
                this.B041 = false,
                this.B051 = false,
                this.B061 = false,
                this.B071 = false,
                this.B081 = false,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                  })
            },
            toogleB031(){
                this.B01 = false,
                this.B02 = false,
                this.B03 = false,
                this.B04 = false,
                this.B05 = false,
                this.B06 = false,
                this.B07 = false,
                this.B08 = false,
                this.B011 = false,
                this.B012 = false,
                this.B013 = false,
                this.B021 = false,
                this.B022 = false,
                this.B031 = ! this.B031,
                this.B041 = false,
                this.B051 = false,
                this.B061 = false,
                this.B071 = false,
                this.B081 = false,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                  })
            },
            toogleB041(){
                this.B01 = false,
                this.B02 = false,
                this.B03 = false,
                this.B04 = false,
                this.B05 = false,
                this.B06 = false,
                this.B07 = false,
                this.B08 = false,
                this.B011 = false,
                this.B012 = false,
                this.B013 = false,
                this.B021 = false,
                this.B022 = false,
                this.B031 = false,
                this.B041 = ! this.B041,
                this.B051 = false,
                this.B061 = false,
                this.B071 = false,
                this.B081 = false,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                  })
            },
            toogleB051(){
                this.B01 = false,
                this.B02 = false,
                this.B03 = false,
                this.B04 = false,
                this.B05 = false,
                this.B06 = false,
                this.B07 = false,
                this.B08 = false,
                this.B011 = false,
                this.B012 = false,
                this.B013 = false,
                this.B021 = false,
                this.B022 = false,
                this.B031 = false,
                this.B041 = false,
                this.B051 = ! this.B051,
                this.B061 = false,
                this.B071 = false,
                this.B081 = false,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                  })
            },
            toogleB061(){
                this.B01 = false,
                this.B02 = false,
                this.B03 = false,
                this.B04 = false,
                this.B05 = false,
                this.B06 = false,
                this.B07 = false,
                this.B08 = false,
                this.B011 = false,
                this.B012 = false,
                this.B013 = false,
                this.B021 = false,
                this.B022 = false,
                this.B031 = false,
                this.B041 = false,
                this.B051 = false,
                this.B061 = ! this.B061,
                this.B071 = false,
                this.B081 = false,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                  })
            },
            toogleB071(){
                this.B01 = false,
                this.B02 = false,
                this.B03 = false,
                this.B04 = false,
                this.B05 = false,
                this.B06 = false,
                this.B07 = false,
                this.B08 = false,
                this.B011 = false,
                this.B012 = false,
                this.B013 = false,
                this.B021 = false,
                this.B022 = false,
                this.B031 = false,
                this.B041 = false,
                this.B051 = false,
                this.B061 = false,
                this.B071 = ! this.B071,
                this.B081 = false,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                  })
            },
            toogleB081(){
                this.B01 = false,
                this.B02 = false,
                this.B03 = false,
                this.B04 = false,
                this.B05 = false,
                this.B06 = false,
                this.B07 = false,
                this.B08 = false,
                this.B011 = false,
                this.B012 = false,
                this.B013 = false,
                this.B021 = false,
                this.B022 = false,
                this.B031 = false,
                this.B041 = false,
                this.B051 = false,
                this.B061 = false,
                this.B071 = false,
                this.B081 = ! this.B081,
                window.scrollTo({
                    top: 350,
                    left: 1400,
                    behavior: 'smooth'
                  })
            },
        }))
    })
